version: "3.3"
services:
  database:
    image: mariadb:10
    volumes:
      - ./mysql/db/entrypoint:/docker-entrypoint-initdb.d/
      - ./mysql/db/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - "13306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=geheim"
      - "MYSQL_DATABASE=termine1"