= Softwareentwicklung im Team: termine1
WS19/20
:icons: font
:icon-set: octicon
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

=== Terminfindung und Abstimmung
Terminfindungen und Abstimmungen sollten essentielle Bestandteile eines guten Systems fuer Bearbeitung und Korrektur/Benotung von Abgaben sein. Haeufig ist es schwierig, neben bekannten Kommilitonen, Kommilitonen zu finden, welche in der gleichen Veranstaltung sitzen und Interesse an Lerngruppen haben. 

==== Problemstellung
Es gibt für Studierende und Mitarbeiter der Uni keine Möglichkeit einfach und schnell Abstimmungen zu erstellen und sich mit Hilfe von Abstimmungen auf Termine zu einigen. Momentan ist eine Terminfindung/Abstimmung nur durch den Einsatz diverser Drittanbieter (Doodle, StrawPoll, ILIAS, WhatsApp ...) möglich. Die Akzeptanz bei wichtigen Entscheidungen ist ohne ein Abstimmungssystem kaum möglich. Die Organisation von Lerngruppen ist in einem anonymen Umfeld (z.B. während einer vorlesung im Hörsaal) nicht ohne weiteres möglich.

==== Wesentliche Features der angepeilten Anwendung
Es sollen im wesentlichen zwei Services für angehörige der HHU angeboten werden: 
Eine Möglichkeit der Terminabstimmung und die Möglichkeit über einzele Fragen abstimmen zu lassen.
Bei beiden Services soll es die Möglichkeit geben die Teilnehmer über Gruppenzugehörigkeit, über einen öffentlichen Link oder über den Usernamen auszuwählen. Bei der Erstellung einer Terminabstimmung bzw. einer Abstimmung sollen mehrere Konfigurations-Einstellungen möglich sein. Für den Nutzer soll ein übersichtliches Dashboard angeboten werden, welches ihn auf die wichtigsten Ereignisse hinweißt. Der Nutzer soll in übersichtlichen Wizard-Steps durch die Konfiguration geführt werden. 
Der Ersteller soll neue Vorschläge für Abstimmungen und Terminfindungen im nachhinein noch ergänzen können und die Teilnehmer sollen darauf entsprechend reagieren können. Ein Nutzer soll möglichst schnell zu einer (Termin)Umfrage navigieren und eine Abstimmung ausführen.Die Ergebnisse einer Abstimmung sollen nach Abschluss übersichtlich aggregiert werden. Nach einer festgelegten Zeit werden alle Daten, verbunden mit einer (Termin)Umfrage, gelöscht. 

==== Dokumentation und wo Sie zu finden ist
Dokumentationen sind grundsätzlich im documentations Ordner im Root Verzeichnis zu finden. Weitere Information lassen sich aus den javadocs entnehmen, sofern vorhanden.


