= Softwareentwicklung im Team: termine1
WS19/20
:icons: font
:icon-set: octicon
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

=== Terminfindung und Abstimmung
Terminfindung umfasst das Erstellen einer Terminumfrage, sowie das Teilnehmen an der Umfrage und die
Präsentation der Ergebnisse. Abstimmungen sind dazu Analog, allerdings wird hier nicht nach einem
gemeinsamen Termin gesucht, sondern nach einem Meinungsbild zu einer gestellten Frage.

==== Problemstellung
Es gibt für Studierende und Mitarbeitende der HHU keine Möglichkeit in einem System der Universität
einfach und schnell Abstimmungen zu erstellen und sich mit Hilfe von Umfragen auf Termine zu einigen. Momentan ist
eine Terminfindung oder Abstimmung nur durch den Einsatz von Drittanbieter-Software
(Doodle, StrawPoll, ILIAS, WhatsApp ...) möglich.

==== Wesentliche Features der angepeilten Anwendung
Es sollen im wesentlichen zwei Services für Angehörige der HHU angeboten werden.
Es soll einen Terminfindungsservice geben und einen Service, der Umfragen zu konkreten Fragestellungen ermöglicht.
Bei beiden Services soll es die Möglichkeit geben, die Teilnehmer der Umfrage über Gruppenzugehörigkeit
oder über den Usernamen zu beschränken. Es sollen auch öffentliche Umfragen gestellt werden können.
Deshalb soll es die Möglichkeit geben, dass ein User per URL auf die Umfrage zugreifen und daran teilnehmen kann.
Der Ersteller wird durch die Erstellung einer Umfrage geführt.
Umfragen können durch den Ersteller konfiguriert werden. Dabei hat er unter anderem die
Möglichkeit zwischen Single-Choice und Multiple-Choice zu wählen.

Für den Nutzer soll ein übersichtliches Dashboard angeboten werden, welches ihn auf die
ihn betreffenden Umfragen hinweist. Des Weiteren soll er neue Vorschläge für Abstimmungen
und Terminfindungen im Nachhinein noch ergänzen können. Nach einer Änderung in einer Umfrage
sollen Teilnehmer der Umfrage entsprechend informiert werden. Ein Nutzer soll möglichst simpel
zu einer Umfrage navigieren und abstimmen können.

Die Ergebnisse einer Abstimmung sollen nach Abschluss der Umfrage übersichtlich angezeigt werden.
Nach einer festgelegten Zeit werden alle Daten, die mit einer Umfrage verbunden sind, gelöscht.

==== Dokumentation und wo Sie zu finden ist
Dokumentationen sind grundsätzlich im documentations Ordner im Root Verzeichnis zu finden.
Weitere Information lassen sich aus den javadocs entnehmen, sofern vorhanden.


