package mops.domain.models;

public enum PollFields {
    QUESTION_POLL_CONFIG, QUESTION_POLL_ENTRY, QUESTION_POLL_METAINF,

    DATE_POLL_CONFIG, DATE_POLL_META_INF, DATE_POLL_ENTRIES,

    CREATOR, PARTICIPANTS, TIMESPAN, POLL_LINK, PARTICIPATING_GROUPS
}
