package mops.domain.models;

public enum PollFields {
    QUESTION_POLL_ACCESSIBILITY, QUESTION_POLL_BALLOT, QUESTION_POLL_CONFIG, QUESTION_POLL_ENTRY, QUESTION_POLL_HEADER,
    QUESTION_POLL_LIFECYCLE, QUESTION_POLL_LINK,

    DATE_POLL_CONFIG, DATE_POLL_LINK, DATE_POLL_META_INF, DATE_POLL_OPTIONS,

    CREATOR, PARTICIPANTS, TIMESPAN
}
