package mops.domain.models;

public enum QuestionPollFields {
    QUESTION_POLL_ACCESSIBILITY, QUESTION_POLL_BALLOT, QUESTION_POLL_CONFIG, QUESTION_POLL_ENTRY, QUESTION_POLL_HEADER,
    QUESTION_POLL_LIFECYCLE, QUESTION_POLL_LINK, CREATOR, PARTICIPANTS, TIMESPAN
}
