package mops.controllers.dtos;

public enum InputFieldNames {
    DATE_POLL_IDENTIFIER, DATE_POLL_LOCATION,
    DATE_POLL_DESCRIPTION, DATE_POLL_LIFECYCLE, DATE_POLL_TITLE_TOO_LONG,
    DATE_POLL_CREATOR, DATE_POLL_OPTION,
    TIMESPAN_INVALID;
}
