name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Check with Checkstyle
      run: ./gradlew checkstyleMain checkstyleTest
    - name: Check with PMD
      run: ./gradlew pmdMain pmdTest
    - name: Check with SpotBugs
      run: ./gradlew spotbugsMain spotbugsTest
